---
- hosts: all

  roles:
    - role: cleanup
      tags: cleanup

    - role: update_device_config
      tags: always

    - setup_system
    - tinc
    - balena-engine
    - containers
    - content_management
