---
- name: Stop services
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - uhttpd.service
    - rabbitmq-server.service
    - django-fastcgi
    - celeryd.service
    - nginx.service
  ignore_errors: yes

- name: Disable services
  systemd:
    name: "{{ item }}"
    enabled: no
  with_items:
    - uhttpd.service
    - rabbitmq-server.service
    - django-fastcgi
    - celeryd.service
    - nginx.service
  ignore_errors: yes

# - name: Enable services
#   systemd:
#     name: "{{ item }}"
#     enabled: yes
#   with_items:
#     - dnsmasq

- name: Remove unwanted packages before upgrading
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:
    - nginx

- name: Remove unwanted files
  file:
    name: "{{ item }}"
    state: absent
  with_items:
   - /etc/nginx/
   # - /lib/systemd/system/ubus.service
   - /lib/systemd/system/contenthub-usb.service
   # - /lib/systemd/system/ubox.service
   - /lib/systemd/system/uhttpd.service
   - /lib/systemd/system/rabbitmq-server.service
   # - /etc/hotplug.d/iface/25-dnsmasq
   - /etc/django-fastcgi
   - /etc/init.d/celeryd
   - /etc/init.d/django-fastcgi
   - /etc/init.d/nginx
   - /etc/init.d/rabbitmq-server
   - /var/www/
   - /media/uploaded
   - /media/preloaded/
   - /customize_brand/
   - /etc/celeryd.default
   - /etc/celeryd.init
   - /etc/config-backup.tar.gz
   - /etc/config-backup.tar.gz.dpkg-old
   - /etc/django-fastcgi
   - /etc/nginx/
   - /etc/nginx.conf
   - /etc/nginx.default
   - /etc/rabbitmq/
   - /srv/
   - /etc/hotplug.d/iface/90-ar2f
