---
- name: Stop services
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - uhttpd.service
    - rabbitmq-server.service
    - django-fastcgi
    - celeryd.service
    - nginx.service
  ignore_errors: yes

- name: Disable services
  systemd:
    name: "{{ item }}"
    enabled: no
  with_items:
    - uhttpd.service
    - rabbitmq-server.service
    - django-fastcgi
    - celeryd.service
    - nginx.service
  ignore_errors: yes

- name: Enable services
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - dnsmasq
    - firewall
    - nodogsplash

- name: Remove unwanted packages
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:
    - nginx
    - contenthub-usb
    - intel-content-hub
    - apport
    - cloud-guest-utils
    - cloud-initramfs-copymods
    - cloud-initramfs-dyn-netconf
    - comgt
    - erlang-base
    - nginx-common
    - nginx-light
    - ppp
    - rabbitmq-server
    - uhttpd

- name: Remove unwanted files
  file:
    name: "{{ item }}"
    state: absent
  with_items:
   - /etc/nginx/
   - /lib/systemd/system/contenthub-usb.service
   - /lib/systemd/system/uhttpd.service
   - /lib/systemd/system/rabbitmq-server.service
   - /etc/django-fastcgi
   - /etc/init.d/celeryd
   - /etc/init.d/django-fastcgi
   - /etc/init.d/nginx
   - /etc/init.d/rabbitmq-server
   - /var/www/
   - /media/uploaded
   - /media/preloaded/
   - /customize_brand/
   - /etc/celeryd.default
   - /etc/celeryd.init
   - /etc/config-backup.tar.gz
   - /etc/config-backup.tar.gz.dpkg-old
   - /etc/django-fastcgi
   - /etc/nginx/
   - /etc/nginx.conf
   - /etc/nginx.default
   - /etc/rabbitmq/
   - /srv/
   - /etc/hotplug.d/iface/90-ar2f
   - /etc/udev/rules.d/81-modem.rules
   - /var/lib/ansible/local/20-firewall
   - /var/lib/ansible/local/25-dnsmasq
