---

- name: Try to synchronize data from local server
  block:
    - mount:
        name: /media/hdd/ideascube-builded
        src: //{{ local_cache_server }}/srv/others/preprod_images/{{project_name}}/ideascube/{{process_id}}/
        fstype: cifs
        opts: guest
        state: mounted
    - command: rsync -a /media/hdd/ideascube-builded/{{ item}}/ ideascube
      with_items:
        - ideascube_var
        - ideascube_cache
  rescue:
    - include: regular_install.yml
  always:
    - mount:
        name: /media/hdd/ideascube-builded
        state: absent
