---
- name: Send start notification.
  command: "{{ callback_fullpath }} 'Starting file copy, this can take quite some time. Go and grab a cup of tea.' {{ ansible_local.device_configuration.process_id }}"

- name: Try to synchronize data from local server
  block:
    - mount:
        name: /media/hdd/ideascube-builded
        src: //{{ local_cache_server }}/ideascube_data/{{project_name}}/ideascube/{{process_id}}/
        fstype: cifs
        opts: guest
        state: mounted
    - command: rsync -a /media/hdd/ideascube-builded/{{ item}}/ /media/hdd/ideascube/
      with_items:
        - var_cache_idc
        - var_idc
    - command: "{{ callback_fullpath }} 'File copy was completed successfully.' {{ ansible_local.device_configuration.process_id }}"
  rescue:
    - command: "{{ callback_fullpath }} --error_lvl WARNING 'Builded install failed, trying regular install.' {{ ansible_local.device_configuration.process_id }}"
    - include: ideascube_regular_install.yml
  always:
    - mount:
        name: /media/hdd/ideascube-builded
        state: absent
  tags:
   - update_content
