---
- name: ideascube - Send start notification.
  command: "{{ callback_fullpath }} 'Starting file copy, this can take quite some time. Go and grab a cup of tea.' {{ ansible_local.device_configuration.process_id }}"

- name: ideascube - Try to synchronize data from local server
  block:
    - name: ideascube - mount local cache server
      mount:
        name: /media/hdd/ideascube-builded
        src: //{{ local_cache_server }}/ideascube_data/{{project_name}}/ideascube/{{process_id}}/
        fstype: cifs
        opts: guest
        state: mounted
    - name: ideascube - import cache tarfiles
      command: tar -xf /media/hdd/ideascube-builded/{{item}} -C /media/hdd/ideascube/
      with_items:
        - var_cache_idc.tar
        - var_idc.tar
    - name: ideascube - notify successful cache tarfiles copy
      command: "{{ callback_fullpath }} 'File copy was completed successfully.' {{ ansible_local.device_configuration.process_id }}"
  rescue:
    - name: ideascube - notify UNsuccessful cache tarfiles copy and fall back to regular install
      command: "{{ callback_fullpath }} --error_lvl WARNING 'Builded install failed, trying regular install.' {{ ansible_local.device_configuration.process_id }}"
    - include: ideascube_regular_install.yml
  always:
    - name: ideascube - umount the local cache server
      mount:
        name: /media/hdd/ideascube-builded
        state: absent
  tags:
   - update_content
