---

- name: Try to synchronize data from local server
  block:
    - mount:
        name: /media/hdd/ideascube-builded
        src: //{{ local_cache_server }}/ideascube_data/{{project_name}}/ideascube/{{process_id}}/
        fstype: cifs
        opts: guest
        state: mounted
    - command: rsync -a /media/hdd/ideascube-builded/{{ item}}/ /media/hdd/ideascube/
      with_items:
        - var_cache_idc
        - var_idc
  rescue:
    - include: ideascube_regular_install.yml
  always:
    - mount:
        name: /media/hdd/ideascube-builded
        state: absent
