---
- name: kolibri - Try to install Kolibri content from local cache server
  block:
    - name: kolibri - mount local cache server
      mount:
        name: /media/hdd/kolibri/kawax
        src: //{{ local_cache_server }}/kolibri
        fstype: cifs
        opts: guest
        state: mounted

    - name: kolibri - Restart container to refresh cifs share
      docker_container:
        docker_host: unix://var/run/balena-engine.sock
        name: "{{ containers[kolibri_index].name }}"
        restart : yes

    - name: kolibri - Import channels and content from local cache server
      raw: >
        {{ kolibri_bin }} manage importchannel disk {{ language[item] }} /root/.kolibri/kawax/khan/{{ item }}/
        && {{ kolibri_bin }} manage importcontent disk {{ language[item] }} /root/.kolibri/kawax/khan/{{ item }}/
      with_items: "{{ containers[kolibri_index].channel_id | default('fr') }}"

    - name: kolibri - umount local cache server
      mount:
        name: /media/hdd/kolibri/kawax
        state: absent

  rescue:
    - name: kolibri - Import channels and content from Internet
      raw: >
        {{ kolibri_bin }} manage importchannel -- network {{ language[item] }}
        && {{ kolibri_bin }} manage importcontent -- network {{ language[item] }}
      with_items: "{{ containers[kolibri_index].channel_id | default('fr') }}"
