---
- name: Copy update content script
  copy:
    src: "50-update-content"
    dest: "/etc/hotplug.d/iface/50-update-content"
    mode: 0755

- include: ideascube.yml
  tags: import_ideascube_content

- include: kolibri.yml
  tags: import_kolibri_content
