---
- name: Copy check cache server script
  template:
    src: "49-cache-server"
    dest: "/etc/hotplug.d/iface/49-cache-server"
    mode: 0755

- include: ideascube.yml
  tags: import_ideascube_content

- include: kolibri.yml
  tags: import_kolibri_content
