---
- name: Ensure the HDD mountpoint exists
  file:
    path: /media/hdd
    state: directory
    mode: 0755

- name: Copy mount units to systemd folder
  copy:
    src: media-hdd.mount
    dest: /etc/systemd/system/media-hdd.mount
    owner: root
    group: root
    mode: 0644

- name: Enable mounts
  command: systemctl enable media-hdd.mount
