- name: Create a volume for the ideascube socket
  docker_volume:
    docker_host: unix://var/run/balena-engine.sock
    name: idc

- name: Pull ideascube from repository and start it
  docker_container:
    docker_host: unix://var/run/balena-engine.sock
    name: "{{ containers[ideascube_index].name }}"
    image: "{{ containers[ideascube_index].image_id }}"
    env:
      IDEASCUBE_ID: "idc"
      DOMAIN: "{{project_type}}"
      DEBUG: "False"
    published_ports: 9000:9000
    restart_policy: always
    state: started
    pull: yes
    labels: "traefik.frontend.rule=Host:{{ containers[ideascube_index].name }}.{{project_type}}"
    entrypoint: "uwsgi --ini /tmp/ideascube.ini --logto /var/log/uwsgi/ideascube.log"
    volumes:
      - /media/hdd/ideascube:/var/ideascube
      - /media/hdd/ideascube:/var/cache/ideascube
      - /media/hdd/log/uwsgi/:/var/log/uwsgi/
      - /media/hdd/config-files/uwsgi/ideascube.ini:/tmp/ideascube.ini
      - idc:/IDCsocket
  tags:
    - pull_container

- name: Get Nginx logs stored in the container
  command: balena-engine cp nginx:/var/log/nginx/ /media/hdd/log/nginx/
  tags:
    - pull_container

- name: Pull Nginx from repository and start it
  docker_container:
    docker_host: unix://var/run/balena-engine.sock
    name: nginx
    image: bibliosansfrontieres/nginx-i386
    published_ports: 8000:80
    restart_policy: always
    state: started
    pull: yes
    labels: traefik.frontend.rule=Host:"{{project_type}},sites.{{project_type}}"
    volumes:
      - /media/hdd/ideascube/static/:/var/ideascube/static/
      - /media/hdd/ideascube/main/media/:/var/ideascube/main/media/
      - /media/hdd/ideascube/mediacenter:/var/ideascube/mediacenter
      - /media/hdd/ideascube/nginx/:/var/ideascube/nginx/
      - /media/hdd/log/nginx/:/var/log/nginx/
      - /media/hdd/config-files/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /media/hdd/config-files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /media/hdd/ideascube/uwsgi_params:/var/ideascube/uwsgi_params
      - idc:/IDCsocket
  tags:
    - pull_container
