---

- name: Create a folder for configuration file
  file:
    path: /media/hdd/{{item}}
    recurse: yes
    state: directory
  with_items:
    - config-files/traefik
    - config-files/nginx
    - config-files/uwsgi
    - ideascube/main
    - hugo/source

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'traefik.toml', dest: '/media/hdd/config-files/traefik/traefik.toml' }
    - { src: 'nginx.conf', dest: '/media/hdd/config-files/nginx/nginx.conf' }
    - { src: 'ideascube.ini', dest: '/media/hdd/config-files/uwsgi/ideascube.ini' }
    - { src: 'uwsgi_params', dest: '/media/hdd/ideascube/'}

- name: Copy configuration templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'default.conf.j2', dest: '/media/hdd/config-files/nginx/default.conf' }

- include: traefik.yml

- include: ideascube.yml

- include: kiwix.yml

- include: kolibri.yml

- include: hugo.yml
