---

- name: Create a folder for configuration file
  file:
    path: /media/hdd/{{item}}
    recurse: yes
    state: directory
  with_items:
    - config-files/traefik
    - config-files/nginx
    - config-files/uwsgi
    - ideascube/main
    - hugo/source
    - olip

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'traefik.toml', dest: '/media/hdd/config-files/traefik/traefik.toml' }
    - { src: 'default.conf', dest: '/media/hdd/config-files/nginx/default.conf' }
    - { src: 'nginx.conf', dest: '/media/hdd/config-files/nginx/nginx.conf' }
    - { src: 'ideascube.ini', dest: '/media/hdd/config-files/uwsgi/ideascube.ini' }
    - { src: 'uwsgi_params', dest: '/media/hdd/ideascube/'}
    - { src: '45-pull-containers', dest: '/etc/hotplug.d/iface/45-pull-containers'}

- include: traefik.yml

- include: ideascube.yml

- include: kiwix.yml

- include: kolibri.yml

- include: olip.yml

- include: hugo.yml
