- name: Copy waybackreplay configuration file
  copy:
    src: config.yaml
    dest: /media/hdd/ideascube/nginx/config.yaml

- name: Pull waybackreplay from repository and start it
  docker_container:
    docker_host: unix://var/run/balena-engine.sock
    name: "sites"
    image: "bibliosansfrontieres/waybackreplay-i386"
    published_ports: 1020:8080
    restart_policy: always
    state: started
    pull: yes
    volumes:
      - /media/hdd/ideascube/nginx/:/webarchive
  tags:
    - pull_container
